version: '3.1'
services:
    postgres:
        image: 'postgres:15-alpine'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=courses
        ports:
            - '12004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '12000:80'

    php-fpm:
        build: php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './php-fpm/php-ini-overrides.ini:/etc/php/8.2/cli/conf.d/99-overrides.ini'
